language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "twentyfour.quinnweber.com"
  skip_cleanup: true
  acl: public_read
  local_dir: build
  region: us-west-2
  on:
    branch: master
env:
  global:
  - secure: GnlvgXJrDUpP3Kpd108oWxJFUzrxN+qjzE3lIpm5aBYYxlOFt5sCqT8hD816evLKWuEQxrqqzgV+3tgXWoKRu+DrTW6Z/GypTNbhjstbNwY6rgb1eXLb0NIrm/dedF6FCW6eP4+oRBiIOgi4UYteWcURufBdNjaDqdHiUDBItfwh9hBcA5jyIoBP8PN+vUaFvzgiWLk0mndCQkZyxj5df7tLRGr5j5cYtFpD+6ak9Skp0JuTsKXwofKRnkZdqSMwUsaQ8TV5PYS66eTqY5EIlJBEnp/nmFKTM2BxPhb0gsyhKcntSP/YunXhR/zettS4ATDDBTZ8E5ApFVKt+AhFvYU0XLXlJKqz7Nf97d5yMp91etUpyegxCyzZpZQODPhoCZM72LgyS2CgwyeE8CHc9UjEP49EAlypQ5a3FLbvdB5TzVm8onTckA7WAZYKbUZ5lyPu2MQV64jze0XFmQlyT37sKr4PXKv8KAtWbSAc0qb3xgokS6qHZvpYLOdKjzPKdjEkOnopOTFI6J1kc2q91LCKXxCj379RvQlKurayMHVs7Z/IQ56+mY73xJDBEuntEhnjdvq/NMFNP3pyxMEvgN9TB1hYXfBANC6xYQkPLb23svH9edOtKlOAhdr40fqt7EwDzUKbiEJKsH3Om7iQyYJE+mdJJQpSX9NHmJVFlaM=
  - secure: aCV2JS8MZsw8+x/P8TBsSMDjHWp4OJfAxs9IdOrNZfxh3PHQeoqPu37pW5smb1UtInfYdI9tt6rwm1xVSkIVp58F9vYWlH5yq1ImwypnsE+cx/sx79nrNkiNtjWKS2X+mhulQQv6JwnxfJPridD2Di6wYWG7Xy3sMOLJtb9CgppFPrcpX74htBhAFhj/wk09Jj2GiE7eA6jpYPi9aoQBVRgMF/oTMnnmGzNVQtPgl4ztQIcV93b5cU+3T2CIAANJcbWkP088V10RPdmIA2o7W5gdB29fKsN3KbeAGuMAwPRSLjbbLiPckFluwzjTeLbMM2WAt/ZJLf24NehqRSzhBe0ioJic6KhL9jDTGzcNsTMW4CUYU7pM8nqf2HU5wbiHB8cn9N73lb4wQ8CYvpv0ist7MG6NXHvsrl+lp9sypxMMRT3jopHg9rcQCj88nTPfx6gKHsm287V0cndC+ClVIM8GzXCb0CZ1h6Kccz6QYhUOweZbfMX+kE6qE204tBhvzKCKXWzd5TW2H5y4uHhaQsTLvCtzY6B20P0U4pq6jnKL8Dea4+C5KzZ+LmEmH3DNuGgf+cZPQT0MX6MGPzq17hDhdHPS1pKuRt1Hvu4wGFcVNYfoH7MmhW8huCU6pu98cZcp6SWvLGkvmu+jaU/wIn/ZE6FWyqHx+hjyw6ipksM=
